on: 

  push: 

    branches: [ main ] 

    paths: 

    #- 'factorial.py' 
    #- 'factorial2.py' 
    #- ' Myfunc.py ' 


 jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@v2 
    - name: Set up Python 3.8 

      uses: actions/setup-python@v2 

      with: 

        python-version: 3.8 

    - name: Install dependencies 

      run: | 

        python -m pip install --upgrade pip 

        pip install pytest 

     #- name: Lint with pylint 

      #run: | 

       # python lint.py 

     - name: Run pytest suite 

     run: | 

        pytest pytest_test.py